// linkedin-scheduler v3 — hands-off content automation
// Publishing itself is handled by the database linkedin-publish-fire/process jobs.
// This function owns content generation, validation, reporting, settings, health, and alerts.

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const cors = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}
const TIMEZONE = 'America/New_York'
const ADMIN_EMAIL = 'info@romylabs.com'
const ADMIN_TENANT = 'a0000000-0000-0000-0000-000000000001'

type Post = { title: string; body: string; category: string; cta_type: string }
const LIBRARY: Post[] = [
 {category:'practitioner',cta_type:'engage',title:'The hidden cost of scattered case notes',body:`A tax resolution case can involve calls, notices, documents, deadlines, follow-ups, and multiple people touching the file.\n\nWhen those details live in separate inboxes, spreadsheets, and personal notes, it becomes harder to answer a simple question: what needs attention next?\n\nThat is one reason I built Tax Res CRM around the day-to-day workflow of a resolution practice.\n\nHow is your firm keeping the full case history in one place?\n\nhttps://taxrescrm.net`},
 {category:'product',cta_type:'demo',title:'A CRM built around tax resolution work',body:`Generic CRMs can track contacts. Tax resolution teams need the surrounding case workflow to make sense too.\n\nTax Res CRM is built specifically around resolution practices: client records, case activity, documents, tasks, communications, and the operational work around an active case.\n\nThe goal is fewer disconnected systems and a clearer picture of what is happening across the office.\n\nWant to see the workflow?\n\nhttps://taxrescrm.net/demo`},
 {category:'founder_story',cta_type:'engage',title:'Why I built Tax Res CRM',body:`I did not start Tax Res CRM because the world needed another generic CRM.\n\nI built it after working inside tax resolution and seeing how much time gets lost moving between systems that were never designed around this type of practice.\n\nThe product decisions come from that perspective: organize the case, make the next action easier to see, and keep the office from depending on scattered information.\n\nhttps://taxrescrm.net`},
 {category:'practitioner',cta_type:'engage',title:'Follow-up should not depend on memory',body:`The easiest follow-up to miss is the one nobody wrote down.\n\nIn a busy tax resolution practice, client callbacks, document requests, IRS follow-ups, and internal tasks compete for attention every day. A repeatable workflow matters more as the caseload grows.\n\nTax Res CRM was built to give resolution teams a clearer place to organize the work instead of relying on memory and disconnected tools.\n\nhttps://taxrescrm.net/demo`},
 {category:'product',cta_type:'demo',title:'One place to see the work',body:`A resolution practice should not need five different places to understand one client relationship.\n\nTax Res CRM brings operational pieces of the practice together so the team has a clearer view of clients, case activity, communications, documents, and tasks.\n\nIt is software built around the work resolution teams already do rather than forcing that work into a generic sales pipeline.\n\nhttps://taxrescrm.net/demo`},
 {category:'practitioner',cta_type:'engage',title:'The case file should tell the story',body:`Open a client file and ask one question: can another person on the team quickly understand what happened, what is pending, and what comes next?\n\nIf the answer depends on finding the right email thread or asking the person who last touched the case, the workflow is carrying unnecessary risk.\n\nA well-organized case history makes handoffs, follow-up, and client communication easier.\n\nhttps://taxrescrm.net`},
 {category:'founder_story',cta_type:'engage',title:'Software should match the practice',body:`One lesson from working in tax resolution: software can create almost as much work as it removes when the workflow does not match the practice.\n\nThat is why I keep coming back to the same question while building Tax Res CRM: would this actually make sense during a normal workday inside a resolution office?\n\nFeatures are useful. A workflow people can actually follow is more useful.\n\nhttps://taxrescrm.net`},
 {category:'practitioner',cta_type:'engage',title:'Visibility matters as the caseload grows',body:`A small caseload can hide a messy process. A larger caseload exposes it.\n\nAs more cases move at the same time, teams need a reliable way to see pending work, recent activity, client communication, and ownership without rebuilding the picture every morning.\n\nThat visibility is one of the core problems Tax Res CRM is designed around.\n\nhttps://taxrescrm.net`},
 {category:'product',cta_type:'demo',title:'Built for resolution teams, not adapted later',body:`There is a difference between adding tax-resolution labels to a generic CRM and designing the workflow around a resolution practice from the beginning.\n\nTax Res CRM is built from the second approach and centered on the operational reality of managing clients and active resolution work.\n\nIf your current system feels like something your firm has had to work around, take a look.\n\nhttps://taxrescrm.net/demo`},
 {category:'practitioner',cta_type:'engage',title:'Good systems make handoffs easier',body:`A good case-management system should make a handoff boring.\n\nThe next person should be able to open the record, understand recent activity, see what is pending, and continue the work without reconstructing the case from messages and memory.\n\nThat becomes increasingly important as a resolution team grows.\n\nhttps://taxrescrm.net`},
 {category:'founder_story',cta_type:'engage',title:'Building from real workflow problems',body:`The best product ideas for Tax Res CRM have not come from a feature checklist. They have come from moments where the work itself felt harder than it needed to be.\n\nA missed handoff. Information in the wrong place. Too many steps to understand a case. A follow-up that should have been obvious.\n\nThose are the problems I want the software to remove.\n\nhttps://taxrescrm.net`},
 {category:'product',cta_type:'demo',title:'See Tax Res CRM in context',body:`The easiest way to evaluate practice software is not a feature list. It is seeing how the workflow fits the way your office actually works.\n\nTax Res CRM is purpose-built for tax resolution practices and the operational work around their cases.\n\nIf you want to see the product in context, book a walkthrough.\n\nhttps://taxrescrm.net/demo`},
]
const BLOCKED=['[draft','[add ','[describe ','[open ','[share ','[verify ','todo','tbd','guaranteed','settle for pennies','eliminate your tax debt','irs approved','irs certified','always works','never fails','fully automated transcript']
function response(x:unknown,status=200){return new Response(JSON.stringify(x),{status,headers:{...cors,'Content-Type':'application/json'}})}
function clean(s:string){return s.toLowerCase().replace(/https?:\/\/\S+/g,'').replace(/[^a-z0-9]+/g,' ').trim()}
function validate(p:Post,recent:string[]){const r:string[]=[];const l=p.body.toLowerCase();if(p.body.length<180)r.push('body_too_short');if(p.body.length>2500)r.push('body_too_long');const urls=p.body.match(/https?:\/\/[^\s]+/g)||[];if(!urls.length||urls.some(u=>!/^https:\/\/taxrescrm\.net(?:[/?]|$)/.test(u)))r.push('invalid_destination');for(const x of BLOCKED)if(l.includes(x))r.push(`blocked:${x}`);const n=clean(p.body);if(recent.some(b=>clean(b)===n))r.push('duplicate_recent_content');return {ok:r.length===0,reasons:r}}
function et(date:Date){const p=new Intl.DateTimeFormat('en-US',{timeZone:TIMEZONE,weekday:'short',hour:'2-digit',hour12:false}).formatToParts(date);return {day:p.find(x=>x.type==='weekday')?.value,hour:Number(p.find(x=>x.type==='hour')?.value)}}
function offset(d:Date){return (new Intl.DateTimeFormat('en-US',{timeZone:TIMEZONE,timeZoneName:'longOffset'}).formatToParts(d).find(x=>x.type==='timeZoneName')?.value||'GMT-04:00').replace('GMT','')}
function slots(from:Date,count=8){const out:{iso:string,label:string}[]=[];const c=new Date(from);c.setUTCHours(12,0,0,0);for(let i=0;i<60&&out.length<count;i++){const p=new Intl.DateTimeFormat('en-US',{timeZone:TIMEZONE,weekday:'short',year:'numeric',month:'numeric',day:'numeric'}).formatToParts(c);const v=(t:string)=>p.find(x=>x.type===t)?.value||'';const wd=v('weekday');if(wd==='Tue'||wd==='Thu'){const y=+v('year'),m=+v('month'),d=+v('day');const probe=new Date(Date.UTC(y,m-1,d,13));const when=new Date(`${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}T09:00:00${offset(probe)}`);if(when>from)out.push({iso:when.toISOString(),label:`${wd==='Tue'?'Tuesday':'Thursday'} ${m}/${d} 9:00 AM ET`})}c.setUTCDate(c.getUTCDate()+1)}return out}
function utm(p:Post,now:Date){const md=new Intl.DateTimeFormat('en-US',{timeZone:TIMEZONE,month:'2-digit',day:'2-digit'}).format(now).replace('/','');return {...p,body:p.body.replace(/https:\/\/taxrescrm\.net(?:\/demo)?/g,u=>`${u}?utm_source=linkedin&utm_medium=social&utm_campaign=li_${p.category}_${md}`)}}
async function recent(sb:any){const since=new Date(Date.now()-30*86400000).toISOString();const {data,error}=await sb.from('linkedin_posts').select('body,category,created_at,scheduled_at,status').eq('tenant_id',ADMIN_TENANT).gte('created_at',since).not('status','eq','failed');if(error)throw error;return data||[]}
async function generate(sb:any,now:Date){const target=slots(now,2),history=await recent(sb),times=target.map(s=>s.iso);const {data:existing,error}=await sb.from('linkedin_posts').select('scheduled_at,status').eq('tenant_id',ADMIN_TENANT).in('scheduled_at',times).not('status','eq','failed');if(error)throw error;const occupied=new Set((existing||[]).map((x:any)=>new Date(x.scheduled_at).toISOString()));const open=target.filter(s=>!occupied.has(new Date(s.iso).toISOString()));const bodies=history.map((x:any)=>x.body||'');const created:any[]=[],quarantined:any[]=[];let cursor=0;for(const slot of open){let source:Post|undefined;for(let tries=0;tries<LIBRARY.length;tries++){const candidate=LIBRARY[(cursor++)%LIBRARY.length];if(validate(candidate,[...bodies,...created.map(x=>x.body||'')]).ok){source=candidate;break}}if(!source){quarantined.push({slot,reasons:['no_unique_valid_content']});continue}const post=utm(source,now),check=validate(post,bodies);if(!check.ok){quarantined.push({slot,title:post.title,reasons:check.reasons});continue}const {data,error:insertError}=await sb.from('linkedin_posts').insert({tenant_id:ADMIN_TENANT,title:post.title,body:post.body,category:post.category,cta_type:post.cta_type,status:'approved',approved_at:now.toISOString(),scheduled_at:slot.iso,retry_count:0}).select('id,title,body,category,status,scheduled_at').single();if(insertError)quarantined.push({slot,title:post.title,reasons:[insertError.message]});else{created.push(data);bodies.push(post.body)}}return {created,quarantined,skipped:target.length-open.length}}
async function alert(sb:any,subject:string,html:string){try{await sb.functions.invoke('send-email',{body:{to:ADMIN_EMAIL,subject,html,tenant_id:ADMIN_TENANT}})}catch(e){console.error('[linkedin-scheduler] alert failed',String(e))}}
async function report(sb:any,now:Date){const since=new Date(now.getTime()-7*86400000).toISOString();const {data:published}=await sb.from('linkedin_posts').select('id,title,category,published_at,linkedin_url').eq('tenant_id',ADMIN_TENANT).eq('status','published').gte('published_at',since);const {data:failed}=await sb.from('linkedin_posts').select('id,title,error_msg,updated_at').eq('tenant_id',ADMIN_TENANT).eq('status','failed').gte('updated_at',since);const {data:upcoming}=await sb.from('linkedin_posts').select('id,title,category,status,scheduled_at').eq('tenant_id',ADMIN_TENANT).in('status',['approved','publishing']).gte('scheduled_at',now.toISOString()).order('scheduled_at',{ascending:true}).limit(10);return {generated_at:now.toISOString(),published:published||[],failed:failed||[],upcoming:upcoming||[]}}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});const url=Deno.env.get('SUPABASE_URL'),key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||Deno.env.get('SB_SERVICE_KEY');if(!url||!key)return response({ok:false,error:'server_configuration_missing'},500);const sb=createClient(url,key);let input:any={};try{input=await req.json()}catch{}const action=input.action||'run',now=new Date();try{if(action==='get_settings'){const {data}=await sb.from('linkedin_settings').select('*').eq('tenant_id',ADMIN_TENANT).maybeSingle();return response({ok:true,settings:{...(data||{}),autopilot:true,timezone:TIMEZONE}})}if(action==='save_settings'){const {error}=await sb.from('linkedin_settings').upsert({tenant_id:ADMIN_TENANT,...(input.settings||{}),autopilot:true,timezone:TIMEZONE,updated_at:now.toISOString()},{onConflict:'tenant_id'});if(error)throw error;return response({ok:true,autopilot:true})}if(action==='get_health'){const {data,error}=await sb.rpc('get_linkedin_health');if(error)throw error;return response({ok:true,health:data})}if(action==='send_alert'){if(!input.subject||!input.html)return response({ok:false,error:'subject_and_html_required'},400);await alert(sb,String(input.subject),String(input.html));return response({ok:true})}if(action==='next_slots')return response({ok:true,slots:slots(now,8)});if(action==='generate_report')return response({ok:true,report:await report(sb,now)});if(action==='list_reports'){const {data,error}=await sb.from('linkedin_weekly_reports').select('*').eq('tenant_id',ADMIN_TENANT).order('week_start',{ascending:false}).limit(12);if(error)throw error;return response({ok:true,reports:data||[]})}if(action==='generate_monday_drafts'||action==='generate_content'){const x=await generate(sb,now);if(x.quarantined.length)await alert(sb,'LinkedIn autopilot: content withheld',`<p>${x.quarantined.length} post(s) failed automated validation and were not approved.</p><pre>${JSON.stringify(x.quarantined,null,2)}</pre>`);return response({ok:true,autopilot:true,...x})}if(action!=='run')return response({ok:false,error:'unknown_action'},400);const clock=et(now),result:any={ok:true,autopilot:true,generated:0,quarantined:0,skipped:0};if(clock.day==='Mon'&&clock.hour===7){const x=await generate(sb,now);result.generated=x.created.length;result.quarantined=x.quarantined.length;result.skipped=x.skipped;result.report=await report(sb,now);if(x.quarantined.length)await alert(sb,'LinkedIn autopilot: validation withheld content',`<p>${x.quarantined.length} post(s) were safely withheld. No invalid content will publish.</p><pre>${JSON.stringify(x.quarantined,null,2)}</pre>`)}return response(result)}catch(e){const msg=e instanceof Error?e.message:String(e);console.error('[linkedin-scheduler]',msg);return response({ok:false,error:msg},500)}})
