// ── Shared email templates ──
// Single source for the Email page's Quick Templates AND the click-to-email
// modal on lead/client records. {name} is replaced with the contact's name.

export const EMAIL_TEMPLATES = [
  { label:'Welcome Letter',         subject:'Welcome to Tax Case Review', body:"Dear {name},\n\nWelcome to Tax Case Review — we're glad to have you on board. Your case has been assigned to a dedicated representative who will be reaching out shortly to walk you through the next steps and what to expect along the way.\n\nIn the meantime, if anything comes up or you have questions, don't hesitate to reach out. We're here to help." },
  { label:'Document Request',       subject:'A Few Documents We Need From You', body:"Dear {name},\n\nTo keep your case moving, we need a few documents from you:\n\n1. Your last 2 years of filed tax returns\n2. Any IRS notices you've received\n3. A copy of your photo ID\n\nYou can upload these directly through your client portal, or reply to this email and we'll guide you through it. The sooner we have these, the sooner we can move forward." },
  { label:'Tax Investigation Update', subject:'Update: Your IRS Investigation', body:"Dear {name},\n\nWe wanted to give you an update on the investigation into your IRS account. This is the part of the process where we pull your full IRS transcripts and review your account history, balances, and any notices on file, so we have a complete and accurate picture before recommending a resolution path.\n\nThis step typically takes some time since it depends on the IRS's own response times, not ours. We'll reach out as soon as we have results to share, and there's nothing you need to do on your end right now." },
  { label:'OIC Update',             subject:'Update on Your Offer in Compromise', body:"Dear {name},\n\nHere's where things stand with your Offer in Compromise (OIC) — this is the IRS program that can let you settle your tax debt for less than the full amount owed. We've submitted your offer, and it's now sitting with the IRS for their review.\n\nThis stage can take several months, since it's entirely on the IRS's timeline. We're monitoring it closely and will let you know the moment there's movement." },
  { label:'Installment Agreement Update', subject:'Update on Your IRS Payment Plan', body:"Dear {name},\n\nWe wanted to update you on your Installment Agreement — this is the monthly payment plan being set up with the IRS so you can pay down your balance over time instead of all at once.\n\nWe're currently working with the IRS to finalize the terms. Once it's approved, we'll send you the full details, including your monthly payment amount and due date." },
  { label:'IRS Notice Response',    subject:"We've Received Your IRS Notice", body:"Dear {name},\n\nWe've received and reviewed the IRS notice on your case, and we're preparing our response on your behalf. No action is needed from you right now — we'll handle the back-and-forth with the IRS directly.\n\nWe'll keep you posted as this develops, and reach out right away if anything changes." },
  { label:'Appointment Reminder',   subject:'Reminder: Your Upcoming Appointment', body:"Dear {name},\n\nJust a friendly reminder of your upcoming appointment with us. If you have any documents we've requested, having them ready ahead of time will help us make the most of our time together.\n\nIf you need to reschedule for any reason, just let us know and we'll find a time that works better." },
  { label:'Documents Still Needed', subject:'Quick Follow-Up: Documents Needed', body:"Dear {name},\n\nWe're still waiting on a few documents to keep your case moving forward. If you've already sent these, please disregard this message — otherwise, we'd really appreciate getting them over to us soon so there's no delay on our end.\n\nIf anything's unclear about what's needed or how to send it, just reply here and we'll help." },
  { label:'Case Status Update',     subject:'An Update on Your Case', body:"Dear {name},\n\nWe wanted to check in and give you a quick update on where your case stands. Things are progressing, and we're continuing to work on your behalf with the IRS.\n\nIf you have any questions in the meantime, feel free to reach out — we're always happy to walk you through where things are." },
  { label:'Resolution Complete',    subject:'Great News — Your Case Is Resolved!', body:"Dear {name},\n\nWe're thrilled to let you know that your tax case has been successfully resolved! This is the moment we've been working toward together, and we couldn't be happier to share this news with you.\n\nThank you for trusting us with something this important — it's been a pleasure working on your behalf." },
  { label:'Payment Receipt',        subject:'Payment Received — Thank You', body:"Dear {name},\n\nThank you — we've received your payment and your account has been updated. We'll continue working diligently on your case, and we appreciate you staying current as we move things forward together." },
  { label:'Penalty Abatement Update', subject:'Update on Your Penalty Relief Request', body:"Dear {name},\n\nWe wanted to update you on the penalty abatement request we filed on your behalf — this is a request asking the IRS to remove or reduce penalties that were added to your balance. We're still waiting to hear back from the IRS on this.\n\nWe'll let you know as soon as we get a decision." },
  { label:'Wage Garnishment Update', subject:'Update on Your Wage Garnishment', body:"Dear {name},\n\nWe wanted to update you on the status of your wage garnishment. We are actively working with the IRS to have this released or reduced, and we understand how stressful this situation can be.\n\nWe're treating this with urgency and will reach out the moment we have news." },
  { label:'1st Strike — Payment', subject:'Payment Reminder: Action Needed on Your Account', body:"Dear {name},\n\nThis is a friendly reminder that we have not yet received your scheduled payment. We understand that things come up, and we want to give you the opportunity to get this resolved before it affects your case.\n\nPlease submit your payment as soon as possible or contact us to discuss your options. We\'re here to help and want to make sure your case stays on track." },
  { label:'2nd Strike — Payment', subject:'Second Notice: Outstanding Payment on Your Account', body:"Dear {name},\n\nThis is our second notice regarding the outstanding payment on your account. As of today, we have not received payment and your balance remains past due.\n\nIf we do not receive payment or hear from you within 5 business days, we may be required to pause work on your case. We strongly encourage you to contact us immediately so we can find a solution together." },
  { label:'3rd Strike — Payment', subject:'Final Notice: Immediate Payment Required', body:"Dear {name},\n\nThis is our final notice regarding the outstanding balance on your account. We have attempted to reach you multiple times and have not received payment or a response.\n\nEffective immediately, all work on your case is suspended until payment is received in full. Continued non-payment may result in termination of our representation agreement.\n\nContact our office within 48 hours to avoid further action." },
  { label:'1st Strike — Documents', subject:'Documents Needed to Proceed With Your Case', body:"Dear {name},\n\nWe are still waiting on documents that are required to move your case forward. Without these, we are unable to take the next steps on your behalf with the IRS.\n\nPlease submit the requested documents through your client portal or reply to this email at your earliest convenience. If you have any questions about what\'s needed or how to send them, we\'re happy to help." },
  { label:'2nd Strike — Documents', subject:'Second Request: Documents Still Outstanding', body:"Dear {name},\n\nThis is our second request for the documents needed on your case. We have not yet received them, and as a result, your case cannot move forward.\n\nDelays in providing documents can have serious consequences with the IRS, including missed deadlines and increased penalties. Please submit the requested documents within 5 business days or contact us immediately if you are having difficulty gathering them." },
  { label:'3rd Strike — Documents', subject:'Final Notice: Case On Hold Pending Documents', body:"Dear {name},\n\nDespite multiple requests, we have not received the required documents for your case. As of today, your case has been placed on hold and we are unable to represent you with the IRS until these items are received.\n\nThis hold may result in missed IRS deadlines, continued enforcement action, or penalties accruing on your account. Contact our office immediately to resolve this matter." },
  { label:'Not Responsible Notice', subject:'Important Notice: Client Liability', body:"Dear {name},\n\nDespite our repeated efforts to assist you, you have not complied with the requirements of our representation agreement, including providing requested documents and/or making scheduled payments.\n\nAs of the date of this notice, our firm is not responsible for any IRS action, penalties, interest, levies, liens, or other enforcement that may result from your non-compliance. We have fulfilled our obligations under our agreement and any further consequences are solely the responsibility of the client.\n\nIf you wish to resume services, please contact our office immediately." },
  { label:'Revoke POA', subject:'Notice of Power of Attorney Revocation', body:"Dear {name},\n\nThis letter serves as formal notice that we are revoking our Power of Attorney (Form 2848) filed on your behalf with the Internal Revenue Service, effective immediately.\n\nWe have filed the revocation directly with the IRS. As a result, we are no longer authorized to represent you, receive correspondence on your behalf, or act in any capacity before the IRS in connection with your tax matter.\n\nYou are now responsible for all communications with the IRS directly. We strongly advise you to retain new representation or contact the IRS promptly regarding any open matters." },
]

export function applyTemplate(t, name) {
  const n = (name || '').trim() || '{name}'
  return { subject: t.subject, body: t.body.replace(/{name}/g, n) }
}
