// ── Shared email templates ──
// Single source for the Email page's Quick Templates AND the click-to-email
// modal on lead/client records. {name} is replaced with the contact's name.

export const EMAIL_TEMPLATES = [
  { label:'Welcome Letter',         subject:'Welcome to Tax Case Review', body:"Dear {name},\n\nWelcome to Tax Case Review — we're glad to have you on board. Your case has been assigned to a dedicated representative who will be reaching out shortly to walk you through the next steps and what to expect along the way.\n\nIn the meantime, if anything comes up or you have questions, don't hesitate to reach out. We're here to help." },
  { label:'Document Request',       subject:'A Few Documents We Need From You', body:"Dear {name},\n\nTo keep your case moving, we need a few documents from you:\n\n1. Your last 2 years of filed tax returns\n2. Any IRS notices you've received\n3. A copy of your photo ID\n\nYou can upload these directly through your client portal, or reply to this email and we'll guide you through it. The sooner we have these, the sooner we can move forward." },
  { label:'Tax Investigation Update', subject:'Update: Your IRS Investigation', body:"Dear {name},\n\nWe wanted to give you an update on the investigation into your IRS account. This is the part of the process where we pull your full IRS transcripts and review your account history, balances, and any notices on file, so we have a complete and accurate picture before recommending a resolution path.\n\nThis step typically takes some time since it depends on the IRS's own response times, not ours. We'll reach out as soon as we have results to share, and there's nothing you need to do on your end right now." },
  { label:'OIC Update',             subject:'Update on Your Offer in Compromise', body:"Dear {name},\n\nHere's where things stand with your Offer in Compromise (OIC) — this is the IRS program that can let you settle your tax debt for less than the full amount owed. We've submitted your offer, and it's now sitting with the IRS for their review.\n\nThis stage can take several months, since it's entirely on the IRS's timeline. We're monitoring it closely and will let you know the moment there's movement." },
  { label:'Installment Agreement Update', subject:'Update on Your IRS Payment Plan', body:"Dear {name},\n\nWe wanted to update you on your Installment Agreement — this is the monthly payment plan being set up with the IRS so you can pay down your balance over time instead of all at once.\n\nWe're currently working with the IRS to finalize the terms. Once it's approved, we'll send you the full details, including your monthly payment amount and due date." },
  { label:'IRS Notice Response',    subject:"We've Received Your IRS Notice", body:"Dear {name},\n\nWe've received and reviewed the IRS notice on your case, and we're preparing our response on your behalf. No action is needed from you right now — we'll handle the back-and-forth with the IRS directly.\n\nWe'll keep you posted as this develops, and reach out right away if anything changes." },
  { label:'Appointment Reminder',   subject:'Reminder: Your Upcoming Appointment', body:"Dear {name},\n\nJust a friendly reminder of your upcoming appointment with us. If you have any documents we've requested, having them ready ahead of time will help us make the most of our time together.\n\nIf you need to reschedule for any reason, just let us know and we'll find a time that works better." },
  { label:'Documents Still Needed', subject:'Quick Follow-Up: Documents Needed', body:"Dear {name},\n\nWe're still waiting on a few documents to keep your case moving forward. If you've already sent these, please disregard this message — otherwise, we'd really appreciate getting them over to us soon so there's no delay on our end.\n\nIf anything's unclear about what's needed or how to send it, just reply here and we'll help." },
  { label:'Case Status Update',     subject:'An Update on Your Case', body:"Dear {name},\n\nWe wanted to check in and give you a quick update on where your case stands. Things are progressing, and we're continuing to work on your behalf with the IRS.\n\nIf you have any questions in the meantime, feel free to reach out — we're always happy to walk you through where things are." },
  { label:'Resolution Complete',    subject:'Great News — Your Case Is Resolved!', body:"Dear {name},\n\nWe're thrilled to let you know that your tax case has been successfully resolved! This is the moment we've been working toward together, and we couldn't be happier to share this news with you.\n\nThank you for trusting us with something this important — it's been a pleasure working on your behalf." },
  { label:'Payment Receipt',        subject:'Payment Received — Thank You', body:"Dear {name},\n\nThank you — we've received your payment and your account has been updated. We'll continue working diligently on your case, and we appreciate you staying current as we move things forward together." },
  { label:'Penalty Abatement Update', subject:'Update on Your Penalty Relief Request', body:"Dear {name},\n\nWe wanted to update you on the penalty abatement request we filed on your behalf — this is a request asking the IRS to remove or reduce penalties that were added to your balance. We're still waiting to hear back from the IRS on this.\n\nWe'll let you know as soon as we get a decision." },
  { label:'Wage Garnishment Update', subject:'Update on Your Wage Garnishment', body:"Dear {name},\n\nWe wanted to update you on the status of your wage garnishment. We are actively working with the IRS to have this released or reduced, and we understand how stressful this situation can be.\n\nWe're treating this with urgency and will reach out the moment we have news." },
]

export function applyTemplate(t, name) {
  const n = (name || '').trim() || '{name}'
  return { subject: t.subject, body: t.body.replace(/{name}/g, n) }
}
