from pathlib import Path
p=Path('public/romylabs-admin-hotfix.js')
s=p.read_text()

needle="""  if (host !== 'admin.romylabs.com') return;\n\n  /* Public meeting/training/invite routes intentionally run on the RomyLabs host"""
insert="""  if (host !== 'admin.romylabs.com') return;\n\n  /* IOS_CHROME_BFCACHE_FIX_V5_20260830: Chrome on iPhone may restore a fully\n   * rendered tenant/demo page from WebKit's back-forward cache without a normal\n   * application boot. Force the dedicated admin control-plane route to evaluate\n   * again whenever such a page is restored, except during validated Jump In. */\n  window.addEventListener('pageshow', function (event) {\n    if (!event.persisted) return;\n    var livePath = window.location.pathname;\n    var liveParams = new URLSearchParams(window.location.search || '');\n    var liveStoredImp = false;\n    try { liveStoredImp = !!sessionStorage.getItem('admin_impersonation'); } catch (_) {}\n    var liveActiveImp = livePath === '/' && liveParams.get('imp') === '1' && liveStoredImp;\n    if (livePath.indexOf('/meet/') === 0 || livePath === '/impersonate' || liveActiveImp) return;\n    window.location.replace('/crm-admin?fresh=' + Date.now());\n  });\n\n  function storedSessionEmail(raw) {\n    if (!raw) return '';\n    try {\n      var parsed = JSON.parse(raw);\n      var direct = parsed && parsed.user && parsed.user.email ? parsed.user.email : '';\n      if (direct) return String(direct).toLowerCase();\n      var token = parsed && parsed.access_token ? parsed.access_token : '';\n      if (!token && Array.isArray(parsed) && parsed[0] && parsed[0].access_token) token = parsed[0].access_token;\n      if (token && token.split('.').length >= 2) {\n        var payload = token.split('.')[1].replace(/-/g, '+').replace(/_/g, '/');\n        while (payload.length % 4) payload += '=';\n        var decoded = JSON.parse(atob(payload));\n        return decoded && decoded.email ? String(decoded.email).toLowerCase() : '';\n      }\n    } catch (_) {}\n    return '';\n  }\n\n  /* Public meeting/training/invite routes intentionally run on the RomyLabs host"""
if needle not in s: raise SystemExit('host boundary pattern missing')
s=s.replace(needle,insert,1)

old="""    var removedTenantAuth = false;\n    try {\n      for (var storageIndex = localStorage.length - 1; storageIndex >= 0; storageIndex--) {\n        var storageKey = localStorage.key(storageIndex);\n        if (!storageKey || storageKey.indexOf('sb-') !== 0 || storageKey.indexOf('-auth-token') === -1) continue;\n        var rawSession = localStorage.getItem(storageKey);\n        if (!rawSession) continue;\n        try {\n          var parsedSession = JSON.parse(rawSession);\n          var storedEmail = parsedSession && parsedSession.user && parsedSession.user.email\n            ? String(parsedSession.user.email).toLowerCase()\n            : '';\n          if (storedEmail && !ownerEmails[storedEmail]) {\n            localStorage.removeItem(storageKey);\n            removedTenantAuth = true;\n          }\n        } catch (_) {}\n      }\n    } catch (_) {}"""
new="""    var removedTenantAuth = false;\n    [localStorage, sessionStorage].forEach(function (store) {\n      try {\n        for (var storageIndex = store.length - 1; storageIndex >= 0; storageIndex--) {\n          var storageKey = store.key(storageIndex);\n          if (!storageKey || storageKey.indexOf('sb-') !== 0 || storageKey.indexOf('-auth-token') === -1) continue;\n          var rawSession = store.getItem(storageKey);\n          var storedEmail = storedSessionEmail(rawSession);\n          if (storedEmail && !ownerEmails[storedEmail]) {\n            store.removeItem(storageKey);\n            removedTenantAuth = true;\n          }\n        }\n      } catch (_) {}\n    });"""
if old not in s: raise SystemExit('session scan pattern missing')
s=s.replace(old,new,1)

p.write_text(s)
print('patched admin iOS session lifecycle v5')
