-- RomyLabs sales agreement / e-sign subsystem.
-- Separate from tenant/client e-sign documents. Platform-admin managed; public access is token-scoped via SECURITY DEFINER RPCs.

create extension if not exists pgcrypto;

create table if not exists public.romylabs_agreement_templates (
  id uuid primary key default gen_random_uuid(),
  product_key text,
  name text not null,
  version text not null default '1.0',
  title text not null,
  body_html text not null,
  active boolean not null default true,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.romylabs_sales_agreements (
  id uuid primary key default gen_random_uuid(),
  prospect_id uuid references public.prospects(id) on delete set null,
  template_id uuid references public.romylabs_agreement_templates(id) on delete set null,
  product_key text not null,
  firm_name text not null,
  signer_name text,
  signer_email text not null,
  seats integer,
  price_per_seat numeric,
  monthly_amount numeric,
  agreement_title text not null,
  agreement_html text not null,
  token_hash text not null unique,
  status text not null default 'draft' check (status in ('draft','sent','viewed','signed','declined','expired','void')),
  sent_at timestamptz,
  opened_at timestamptz,
  signed_at timestamptz,
  declined_at timestamptz,
  expires_at timestamptz,
  signed_name text,
  signer_ip text,
  signer_user_agent text,
  signature_text text,
  sent_by text,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.romylabs_sales_agreement_events (
  id bigint generated by default as identity primary key,
  agreement_id uuid not null references public.romylabs_sales_agreements(id) on delete cascade,
  event_type text not null check (event_type in ('created','sent','opened','signed','declined','resent','voided','expired')),
  actor text,
  ip_address text,
  user_agent text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.romylabs_agreement_templates enable row level security;
alter table public.romylabs_sales_agreements enable row level security;
alter table public.romylabs_sales_agreement_events enable row level security;

drop policy if exists "platform admins manage agreement templates" on public.romylabs_agreement_templates;
create policy "platform admins manage agreement templates" on public.romylabs_agreement_templates for all to authenticated using (public._is_platform_admin()) with check (public._is_platform_admin());
drop policy if exists "platform admins manage sales agreements" on public.romylabs_sales_agreements;
create policy "platform admins manage sales agreements" on public.romylabs_sales_agreements for all to authenticated using (public._is_platform_admin()) with check (public._is_platform_admin());
drop policy if exists "platform admins read agreement events" on public.romylabs_sales_agreement_events;
create policy "platform admins read agreement events" on public.romylabs_sales_agreement_events for select to authenticated using (public._is_platform_admin());

create unique index if not exists romylabs_agreement_templates_active_product_uq
  on public.romylabs_agreement_templates (coalesce(product_key,'*'), version) where active=true;

insert into public.romylabs_agreement_templates(product_key,name,version,title,body_html,active,created_by)
select null,'RomyLabs SaaS Subscription Agreement','1.0','RomyLabs SaaS Subscription Agreement',
$$<h2>RomyLabs SaaS Subscription Agreement</h2>
<p>This SaaS Subscription Agreement (the “Agreement”) is entered into between <strong>RomyLabs</strong> (“RomyLabs”) and <strong>{{firm_name}}</strong> (“Customer”) for access to <strong>{{product_name}}</strong>.</p>
<h3>1. Subscription</h3><p>Customer is subscribing to {{product_name}} for <strong>{{seats}} seats</strong> at <strong>${{price_per_seat}} per seat per month</strong>, for a current monthly subscription amount of <strong>${{monthly_amount}}</strong>. Additional seats or agreed service changes may change the monthly amount.</p>
<h3>2. Billing and Payment</h3><p>Subscription fees are billed monthly unless the parties agree otherwise in writing. Customer agrees to pay all undisputed amounts when due. Past-due access may be limited or suspended under the applicable RomyLabs billing policy after required notices are provided.</p>
<h3>3. Customer Data</h3><p>Customer retains ownership of Customer data submitted to the service. RomyLabs may process Customer data only as needed to provide, secure, support, maintain, and improve the subscribed service and as otherwise permitted by law or this Agreement.</p>
<h3>4. Authorized Use</h3><p>Customer will use the service only for lawful business purposes and will maintain reasonable controls over user credentials and account access. Customer is responsible for activity performed through its authorized users.</p>
<h3>5. Service and Support</h3><p>RomyLabs will use commercially reasonable efforts to operate and support the service. Maintenance, upgrades, security work, third-party outages, internet failures, and events outside reasonable control may affect availability.</p>
<h3>6. Confidentiality</h3><p>Each party will use reasonable care to protect non-public confidential information received from the other party and will use that information only for purposes related to the business relationship, except where disclosure is required by law.</p>
<h3>7. Term and Cancellation</h3><p>The subscription begins when access is activated and continues month-to-month unless a different term is stated in an order or addendum. Either party may end a month-to-month subscription by written notice before the next billing period, subject to any outstanding payment obligations.</p>
<h3>8. Suspension and Termination</h3><p>RomyLabs may suspend access for material breach, security risk, unlawful use, or unpaid undisputed fees after applicable notice and cure periods. Suspension does not delete Customer data.</p>
<h3>9. Warranties and Liability</h3><p>Except as expressly stated in this Agreement, the service is provided on an “as available” basis to the maximum extent permitted by law. Neither party is liable for indirect, incidental, special, exemplary, or consequential damages arising from this Agreement.</p>
<h3>10. Governing Law</h3><p>This Agreement is governed by the laws of the State of Florida, without regard to conflict-of-law principles, unless the parties agree otherwise in writing.</p>
<h3>11. Electronic Signature</h3><p>The parties agree that electronic signatures and electronic records have the same force and effect as handwritten signatures and paper records to the extent permitted by applicable law.</p>
<h3>12. Entire Agreement</h3><p>This Agreement, together with any signed order form, addendum, privacy terms, or other incorporated terms, represents the agreement between the parties regarding the subscribed service.</p>
<p><strong>Customer:</strong> {{firm_name}}<br/><strong>Signer:</strong> {{signer_name}}<br/><strong>Email:</strong> {{signer_email}}<br/><strong>Product:</strong> {{product_name}}<br/><strong>Seats:</strong> {{seats}}<br/><strong>Monthly Amount:</strong> ${{monthly_amount}}</p>$$,
true,'system'
where not exists (select 1 from public.romylabs_agreement_templates where active=true and product_key is null and version='1.0');

-- RPC implementations are deployed in production by migration romylabs_sales_agreement_workflow_v2
-- and romylabs_sales_agreement_resend_token. This file tracks the durable table/RLS/template contract.
