-- ============================================================================
-- Table + seed data: State LLC Formation Requirements (FormaCorp)
-- Source: state Secretary of State sites, verified Jan 2026 fee tables
-- ============================================================================

CREATE TABLE IF NOT EXISTS state_formation_requirements (
  id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  state text UNIQUE NOT NULL,
  state_name text NOT NULL,
  llc_filing_fee text,
  annual_report_fee text,
  processing_time text,
  sos_url text,
  notes text,
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE state_formation_requirements ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow read for authenticated" ON state_formation_requirements;
CREATE POLICY "Allow read for authenticated" ON state_formation_requirements
  FOR SELECT USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Allow all for authenticated" ON state_formation_requirements;
CREATE POLICY "Allow all for authenticated" ON state_formation_requirements
  FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('AL', 'Alabama', '$200', '$50 (Annual Report + Min. Business Privilege Tax)', 'Same day', 'https://sos.alabama.gov/business-entities', 'Files with AL Secretary of State; also requires Business Privilege Tax registration with AL Dept. of Revenue.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('AK', 'Alaska', '$250', '$100 (biennial)', 'Same day', 'https://www.commerce.alaska.gov/web/cbpl/', 'Files with Division of Corporations, Business & Professional Licensing.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('AZ', 'Arizona', '$50', '$0 (no annual report)', '14-16 business days', 'https://ecorp.azcc.gov', 'No annual report required, but new LLCs must publish notice of formation in an approved newspaper for 3 consecutive weeks ($50-$300 depending on county).') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('AR', 'Arkansas', '$45', '$150 (Annual Franchise Tax Report)', '3-7 business days', 'https://www.sos.arkansas.gov/business-commercial-services-bcs', 'Annual franchise tax report due May 1 each year.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('CA', 'California', '$70', '$20 (biennial Statement of Information) + $800/yr Franchise Tax', '2-3 business days', 'https://bizfileonline.sos.ca.gov', '$800 minimum annual franchise tax applies even to dormant LLCs (FTB Form 568).') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('CO', 'Colorado', '$50', '$10 (Periodic Report)', 'Same day', 'https://www.coloradosos.gov/biz', 'Periodic report due annually during anniversary month; cheapest ongoing cost.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('CT', 'Connecticut', '$120', '$80 (Annual Report)', '2-3 business days', 'https://service.ct.gov/business', 'Annual report due by anniversary date.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('DE', 'Delaware', '$110', '$300 (Annual LLC Tax)', '10 business days', 'https://corp.delaware.gov', 'Flat $300 annual tax due June 1, regardless of income or activity; no annual report required.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('DC', 'Washington D.C.', '$99', '$300 (biennial Two-Year Report)', '5 business days', 'https://corponline.dcra.dc.gov', 'Biennial report due April 1 of even years.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('FL', 'Florida', '$125', '$138.75 (Annual Report)', '5 business days', 'https://dos.myflorida.com/sunbiz/manage-business/efile/', 'Annual report due between Jan 1 - May 1; $400 late fee if missed.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('GA', 'Georgia', '$100', '$50 (Annual Registration)', '7-10 business days', 'https://ecorp.sos.ga.gov', 'Annual registration due between Jan 1 - Apr 1. Publication of formation notice recommended ($40-$100).') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('HI', 'Hawaii', '$50', '$15 (Annual Report)', '10-15 business days', 'https://hbe.ehawaii.gov', 'Annual report due during the quarter that includes the anniversary month.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('ID', 'Idaho', '$100', '$0 (no annual report fee)', '5-7 business days', 'https://sosbiz.idaho.gov', 'Must file a free annual report to remain in good standing, even though there''s no fee.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('IL', 'Illinois', '$150', '$75 (Annual Report)', '5-10 business days', 'https://www.ilsos.gov/departments/business_services/home.html', 'Annual report due before the first day of the anniversary month.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('IN', 'Indiana', '$95', '$31 (biennial Business Entity Report)', '1 business day', 'https://inbiz.in.gov', 'Biennial report due by the end of the anniversary month, every other year.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('IA', 'Iowa', '$50', '$30 (biennial Biennial Report)', '1 business day', 'https://sos.iowa.gov/business/', 'Biennial report due by Apr 1 of odd-numbered years.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('KS', 'Kansas', '$160', '$55 (Annual Report)', 'Same day', 'https://sos.ks.gov/business/business.html', 'Annual report due by the 15th day of the 4th month after the tax closing month.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('KY', 'Kentucky', '$40', '$15 (Annual Report)', 'Same day', 'https://sos.ky.gov/bus/Pages/default.aspx', 'Lowest filing fee in the country; annual report due by June 30.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('LA', 'Louisiana', '$100', '$35 (Annual Report)', '3-5 business days', 'https://www.sos.la.gov/BusinessServices', 'Annual report due on anniversary of formation date.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('ME', 'Maine', '$175', '$85 (Annual Report)', '10-15 business days', 'https://www.maine.gov/sos/cec/corp/', 'Annual report due by June 1 each year.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('MD', 'Maryland', '$100', '$300 (Annual Report + Personal Property Return)', '2 weeks', 'https://egov.maryland.gov/businessexpress', 'Annual report/personal property return due Apr 15.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('MA', 'Massachusetts', '$500', '$500 (Annual Report)', '1-2 business days', 'https://corp.sec.state.ma.us/CorpWeb/', 'Highest filing fee and annual report fee in the country; annual report due on anniversary date.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('MI', 'Michigan', '$50', '$25 (Annual Statement)', '7-10 business days', 'https://cofs.lara.state.mi.us', 'Annual statement due Feb 15 each year.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('MN', 'Minnesota', '$155', '$0 (no annual report fee)', 'Same day', 'https://mblsportal.sos.state.mn.us', 'Must file a free annual renewal by Dec 31 to remain active.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('MS', 'Mississippi', '$50', '$0 (Annual Report required, no fee)', '1-2 business days', 'https://corp.sos.ms.gov', 'Free annual report due by Apr 15.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('MO', 'Missouri', '$50', '$0 (no annual report required)', 'Same day', 'https://bsd.sos.mo.gov', 'No annual report or franchise tax for LLCs - lowest ongoing cost.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('MT', 'Montana', '$35', '$20 (Annual Report)', '5-6 business days', 'https://biz.sosmt.gov', 'Lowest filing fee in the country; annual report due by Apr 15.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('NE', 'Nebraska', '$100', '$10 (biennial Biennial Report)', '2-3 business days', 'https://www.nebraska.gov/sos/corp/', 'Biennial report due by Apr 1 of odd years. Publication of formation notice required for 3 weeks ($100-$200).') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('NV', 'Nevada', '$425', '$150 (Annual List) + $200 (State Business License)', '1 business day', 'https://www.nvsilverflume.gov', 'Highest combined ongoing cost ($350/yr); both due on anniversary month.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('NH', 'New Hampshire', '$100', '$100 (Annual Report)', '7-10 business days', 'https://quickstart.sos.nh.gov', 'Annual report due by Apr 1.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('NJ', 'New Jersey', '$125', '$75 (Annual Report)', '1 business day', 'https://www.njportal.com/dor/businessformation', 'Annual report due by the end of the anniversary month.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('NM', 'New Mexico', '$50', '$0 (no annual report required)', '1-3 business days', 'https://enterprise.sos.nm.gov', 'No annual report or franchise tax - one of the lowest maintenance states.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('NY', 'New York', '$205', '$9 (biennial Statement)', 'Same day', 'https://dos.ny.gov/division-corporations', 'Biennial statement due in the anniversary month. Publication requirement: 2 newspapers (1 daily, 1 weekly) for 6 weeks - cost varies $50 to $1,500+ by county.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('NC', 'North Carolina', '$125', '$200 (Annual Report)', '2-5 business days', 'https://www.sosnc.gov/divisions/business_registration', 'Annual report due Apr 15.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('ND', 'North Dakota', '$135', '$50 (Annual Report)', '5 business days', 'https://firststop.sos.nd.gov', 'Annual report due by Nov 15.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('OH', 'Ohio', '$99', '$0 (no annual report required)', '1 business day', 'https://businesssearch.ohiosos.gov', 'No annual report or franchise tax for LLCs.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('OK', 'Oklahoma', '$100', '$25 (Annual Certificate)', '2-3 business days', 'https://www.sos.ok.gov/corp/', 'Annual certificate due by anniversary date.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('OR', 'Oregon', '$100', '$100 (Annual Report)', '2-3 business days', 'https://sos.oregon.gov/business/Pages/default.aspx', 'Annual report due by anniversary date.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('PA', 'Pennsylvania', '$125', '$70 (decennial report, every 10 years)', '5-7 business days', 'https://www.pa.gov/agencies/dos/programs/business-and-charitable-organizations.html', 'Report only due once per decade - very low ongoing maintenance.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('RI', 'Rhode Island', '$150', '$50 (Annual Report)', '3-4 business days', 'https://web.sos.ri.gov/business', 'Annual report due Nov 1 - Mar 1.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('SC', 'South Carolina', '$110', '$0 (no annual report required)', '1-2 business days', 'https://businessfilings.sc.gov', 'No annual report required for LLCs (unless taxed as S-Corp).') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('SD', 'South Dakota', '$150', '$50 (Annual Report)', 'Same day', 'https://sosenterprise.sd.gov', 'Annual report due by the first day of anniversary month.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('TN', 'Tennessee', '$300', '$300 (Annual Report)', 'Same day', 'https://tnbear.tn.gov/Ecommerce/', 'Annual report due on 1st day of 4th month after fiscal year end.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('TX', 'Texas', '$300', '$0 (Franchise Tax ''No Tax Due'' Report instead)', '13-15 business days', 'https://www.sos.state.tx.us/corp/index.shtml', 'No flat annual report fee, but franchise tax report (often $0 for small LLCs under $2.47M revenue) due May 15.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('UT', 'Utah', '$59', '$20 (Annual Report)', 'Same day', 'https://corporations.utah.gov', 'Annual report due by anniversary month.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('VT', 'Vermont', '$155', '$35 (Annual Report)', '1 business day', 'https://sos.vermont.gov/corporations/', 'Annual report due within 3 months of fiscal year end.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('VA', 'Virginia', '$100', '$50 (Annual Registration Fee)', '2-5 business days', 'https://cis.scc.virginia.gov', 'Annual registration fee due by last day of formation anniversary month.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('WA', 'Washington', '$200', '$60 (Annual Report)', '5 business days', 'https://www.sos.wa.gov/corporations-charities', 'Annual report due by end of anniversary month.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('WV', 'West Virginia', '$100', '$25 (Annual Report)', '5-10 business days', 'https://apps.wv.gov/sos/business/', 'Annual report due by July 1.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('WI', 'Wisconsin', '$130', '$25 (Annual Report)', 'Same day', 'https://www.wdfi.org/apps/CorpSearch/', 'Annual report due by end of registration anniversary quarter.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
INSERT INTO state_formation_requirements (state, state_name, llc_filing_fee, annual_report_fee, processing_time, sos_url, notes) VALUES ('WY', 'Wyoming', '$100', '$60 (minimum, License Tax)', 'Same day', 'https://wyobiz.wyo.gov', 'Annual report/license tax (greater of $60 or $0.0002 x in-state assets) due on first day of anniversary month.') ON CONFLICT (state) DO UPDATE SET state_name=EXCLUDED.state_name, llc_filing_fee=EXCLUDED.llc_filing_fee, annual_report_fee=EXCLUDED.annual_report_fee, processing_time=EXCLUDED.processing_time, sos_url=EXCLUDED.sos_url, notes=EXCLUDED.notes, updated_at=now();
