-- ============================================================================
-- Seed data: State Tax Authority Reference Info
-- Category 'State Info', one row per phone/fax/email/address line
-- ============================================================================

INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Department of Revenue', '(334) 242-1170', NULL, 'AL', 1);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Collections', '(334) 242-1220', NULL, 'AL', 2);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax', '(334) 242-8914', NULL, 'AL', 3);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax (Collections)', '(334) 242-8342', NULL, 'AL', 4);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Collections', '(602) 542-5551', NULL, 'AZ', 5);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax', '(602) 716-6008', NULL, 'AZ', 6);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'POA Email', 'POA@azdor.gov', NULL, 'AZ', 7);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'General Line', '(800) 882-9275', NULL, 'AR', 8);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Collections', '(501) 682-5000', NULL, 'AR', 9);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Income Tax Dept', '(501) 682-1100', NULL, 'AR', 10);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax', '(501) 682-3534', NULL, 'AR', 11);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'POA Email', 'collections.research@dfa.arkansas.gov', NULL, 'AR', 12);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Practitioner', '(916) 845-7057', NULL, 'CA', 13);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Bankruptcy', '(916) 845-4750', NULL, 'CA', 14);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Collections', '(866) 418-3702', NULL, 'CA', 15);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Biz Collections', '(916) 845-7033', NULL, 'CA', 16);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Account Recovery', '(888) 382-3707', NULL, 'CA', 17);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'General Line', '(800) 852-5711', NULL, 'CA', 18);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Business Recovery', '(888) 635-0494', NULL, 'CA', 19);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Accounts Receivable', '(800) 689-4776', NULL, 'CA', 20);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Complex Accounts', '(916) 845-7051', NULL, 'CA', 21);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Payment Plan', '(800) 689-4776', NULL, 'CA', 22);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Collections Fax', '(916) 845-0413', NULL, 'CA', 23);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Account Recovery Fax', '(916) 843-2425', NULL, 'CA', 24);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'EDD Collections', '(888) 435-4990', NULL, 'CA', 25);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Collections Revivor Account', '(888) 635-0494', NULL, 'CA', 26);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'EDD Fax', '(916) 654-9211', NULL, 'CA', 27);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Secretary of State', '916-657-3537', NULL, 'CA', 28);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Court Ordered Debt Asst. Line', '(916) 845-5085', NULL, 'CA', 29);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'CDTFA Top 500 Unit', '(916) 845-7874', NULL, 'CA', 30);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Collections', '(303) 205-8291', NULL, 'CO', 31);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'General Line', '(303) 238-7378', NULL, 'CO', 32);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax', '(303) 866-2037 or 4771', NULL, 'CO', 33);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Discovery Division', '(303) 866-3018', NULL, 'CO', 34);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Dept. of Revenue Services', '(860) 297-5962', NULL, 'CT', 35);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Collections', '(860) 297-4936', NULL, 'CT', 36);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Audit', '(860) 541-4936', NULL, 'CT', 37);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Audit Fax', '(860) 297-5843', NULL, 'CT', 38);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'POA Note', NULL, 'POA needs to be faxed to Rep', 'CT', 39);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Collections', '(302) 577-8785', NULL, 'DE', 40);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Taxpayer Assistance', '(850) 488-6800', 'Option 4, then option 5', 'FL', 41);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Registration', '(850) 717-6628', NULL, 'FL', 42);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Registration Fax', '(850) 488-5997', NULL, 'FL', 43);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'POA Email', 'acctmaint@floridarevenue.com', NULL, 'FL', 44);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Personal', '(877) 423-6711', 'Option 3', 'GA', 45);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Collections', '(404) 417-2122', NULL, 'GA', 46);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Business', '(877) 423-6711', 'Ask agent to transfer to Atlanta regional office', 'GA', 47);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax', '(404) 417-6589', NULL, 'GA', 48);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Online Portal', 'https://gtc.dor.ga.gov/_/', NULL, 'GA', 49);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Personal', '(800) 222-3229', NULL, 'HI', 50);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax', '(808) 587-1488', NULL, 'HI', 51);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Collections', '(208) 334-7660', NULL, 'ID', 52);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'General Line', '(800) 732-8866', NULL, 'IL', 53);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Business Hot Line', '(217) 524-4772', NULL, 'IL', 54);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Collections', '(217) 785-2698', NULL, 'IL', 55);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Bank Levy', '(217) 524-4720', NULL, 'IL', 56);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax', '(217) 785-2635', NULL, 'IL', 57);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Wage Levy', '(217) 557-9472', NULL, 'IL', 58);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'POA Email', 'rev.poa@illinois.gov', NULL, 'IL', 59);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Jason — Collection Agency Accounts', '(217) 785-5212, ext. 31334', NULL, 'IL', 60);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax for SFR Returns', '(217) 785-6003', NULL, 'IL', 61);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Individual', '(317) 232-2240', NULL, 'IN', 62);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Collections', '(317) 232-2165', NULL, 'IN', 63);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax', '(317) 234-4161', NULL, 'IN', 64);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Collections', '(866) 339-7912', NULL, 'IA', 65);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax — POA', '(515) 281-3906', NULL, 'IA', 66);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax — Collections (after appeal period expires)', '(515) 725-0264', NULL, 'IA', 67);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax — Examination Section', '(515) 281-3756', NULL, 'IA', 68);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax — Business Registration', '(515) 281-3906', NULL, 'IA', 69);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax — Taxpayer Services', '(515) 281-3114', NULL, 'IA', 70);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax — Payment Processing', '(515) 281-5830', NULL, 'IA', 71);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Taxpayer Services', '(800) 367-3388', NULL, 'IA', 72);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Collections', '(785) 296-6121', NULL, 'KS', 73);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax', '(785) 291-3616', NULL, 'KS', 74);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'General', '(502) 564-4581', NULL, 'KY', 75);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Collections', '(502) 564-4921', NULL, 'KY', 76);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Collections Fax', '(502) 564-9571', NULL, 'KY', 77);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Collections (2)', '(502) 564-5354', NULL, 'KY', 78);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Collections Fax (2)', '(502) 564-3875', NULL, 'KY', 79);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax', '(502) 564-3875', NULL, 'KY', 80);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Headquarters', '(855) 307-3893', NULL, 'LA', 81);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Levy Dept.', '(225) 219-7318', 'Option for levy dept.', 'LA', 82);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Levy Fax', '(225) 219-0866', NULL, 'LA', 83);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax', '(225) 952-2537', NULL, 'LA', 84);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Compliance', '(207) 624-9595', NULL, 'ME', 85);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Practitioner', '(207) 626-8458', NULL, 'ME', 86);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax', '(207) 287-6627', NULL, 'ME', 87);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Tax Return Fax', '(207) 621-4356', NULL, 'ME', 88);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Practitioner', '(410) 260-7424', NULL, 'MD', 89);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Collections', '(410) 974-2432', NULL, 'MD', 90);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax', '(410) 260-6213', NULL, 'MD', 91);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Collections Email', 'cdcollectionind@comp.state.md.us', NULL, 'MD', 92);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'POA Email', 'radpoa@comp.state.md.us', NULL, 'MD', 93);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'General', '(617) 887-6367', NULL, 'MA', 94);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Collections', '(617) 887-6400', NULL, 'MA', 95);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax', '(617) 660-3995', NULL, 'MA', 96);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'General', '(517) 636-4486', NULL, 'MI', 97);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Collections', '(517) 636-5265', 'Option 1, option 6', 'MI', 98);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'POA Fax', '(517) 272-5561', NULL, 'MI', 99);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'General Fax', '(517) 636-4488', NULL, 'MI', 100);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Collections Fax', '(517) 636-5393', NULL, 'MI', 101);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Accounts Receivable Services', '(800) 950-6227', NULL, 'MI', 102);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'A/R Services Fax', '(517) 272-5561 or 5562', NULL, 'MI', 103);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Income Tax Dept.', '(800) 657-3666', NULL, 'MN', 104);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Collections', '(651) 556-3003', NULL, 'MN', 105);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax', '(651) 556-5210', NULL, 'MN', 106);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Customer Service', '(601) 923-7700', NULL, 'MS', 107);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Collections', '(601) 923-7391', NULL, 'MS', 108);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax', '(601) 923-7714', NULL, 'MS', 109);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax (alt)', '(601) 923-7039', NULL, 'MS', 110);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Mail POA', 'PO Box 2338, Jackson, MI 39225', NULL, 'MS', 111);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'General', '(573) 751-3505', NULL, 'MO', 112);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Garnishment', '(573) 522-6276', 'Option 2, then 5', 'MO', 113);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Taxation', '(573) 751-7200', NULL, 'MO', 114);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax', '(573) 751-2195', NULL, 'MO', 115);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax (alt)', '(573) 522-6922', NULL, 'MO', 116);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Online Chat', 'https://dora.chat/', NULL, 'MO', 117);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'General', '(866) 859-2254', NULL, 'MT', 118);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Individual Line', '(406) 444-6964', 'Call here first', 'MT', 119);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Collections', '(406) 444-6964', NULL, 'MT', 120);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Collections Fax', '(406) 444-7723', NULL, 'MT', 121);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Income Taxes Fax', '(406) 444-6642', NULL, 'MT', 122);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Email for Returns', 'dorcollections@mt.gov', 'Subject: "Priority Processing, Attn: Lee Keller"', 'MT', 123);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'General', '(800) 742-7474', 'Option 5', 'NE', 124);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax', '(402) 471-5927', NULL, 'NE', 125);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Customer Service', '(609) 292-6400', NULL, 'NJ', 126);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Personal', '(609) 633-6657', NULL, 'NJ', 127);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Business', '(609) 633-6905', NULL, 'NJ', 128);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Judgment Dept.', '(609) 292-7331', NULL, 'NJ', 129);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Judgment Dept. Fax', '(609) 292-9266', NULL, 'NJ', 130);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax', '(609) 633-8427', NULL, 'NJ', 131);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Pioneer Credit Recovery', '(866) 372-6840', NULL, 'NJ', 132);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Pioneer Fax', '(888) 478-7563', NULL, 'NJ', 133);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Audit and Compliance', '(505) 827-0951', NULL, 'NM', 134);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Acct. Resolutions Fax', '(505) 841-6327', NULL, 'NM', 135);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Call Center', '(866) 285-2996', NULL, 'NM', 136);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax', '(505) 841-6327', NULL, 'NM', 137);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Business Registration Email', 'Business.reg@state.nm.us', NULL, 'NM', 138);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Levy Dept.', '(505) 841-6284', NULL, 'NM', 139);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Levy Email', 'trd-levy@state.nm.us', NULL, 'NM', 140);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'General', '(505) 827-0700', NULL, 'NM', 141);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'General (alt)', '(505) 690-5603', NULL, 'NM', 142);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Practitioner', '(518) 457-5181', NULL, 'NY', 143);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Personal Income', '(518) 457-5451', NULL, 'NY', 144);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Business Corporations', '(518) 485-6027', NULL, 'NY', 145);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Collections', '(518) 457-5434', 'Call here for business', 'NY', 146);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'OIC Unit', '(518) 457-9086', NULL, 'NY', 147);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Sales Tax', '(518) 485-2889', NULL, 'NY', 148);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax', '(518) 435-8617', NULL, 'NY', 149);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'General', '(877) 252-3052', NULL, 'NC', 150);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Collections', '(910) 254-5000', NULL, 'NC', 151);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax', '(919) 715-1786', NULL, 'NC', 152);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax (alt)', '(919) 733-5750', NULL, 'NC', 153);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'General', '(701) 328-7088', NULL, 'ND', 154);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Attorney General', '(888) 301-8885', NULL, 'OH', 155);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Attorney General Fax', '(614) 752-9070', NULL, 'OH', 156);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'General Revenue Corp', '(800) 436-5244', NULL, 'OH', 157);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'General Revenue Corp Fax', '(866) 949-2849', NULL, 'OH', 158);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Tax Lien/Warrant Dept.', '(405) 522-4193', NULL, 'OK', 159);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Personal Income Tax', '(405) 521-3160', NULL, 'OK', 160);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Business Income Tax', '(405) 521-3126', NULL, 'OK', 161);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax', '(405) 521-2434', NULL, 'OK', 162);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'General', '(503) 378-4988', NULL, 'OR', 163);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Collections', '(503) 947-1710', NULL, 'OR', 164);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Employment Dept. Fax', '(503) 947-1376', NULL, 'OR', 165);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Dept. of Revenue Fax', '(503) 945-8772', NULL, 'OR', 166);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Compliance', '(717) 787-3911', NULL, 'PA', 167);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Personal Taxes', '(717) 787-8201', NULL, 'PA', 168);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Collections', '(717) 783-3000', NULL, 'PA', 169);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Penn Credit', '(717) 238-7124', NULL, 'PA', 170);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'LGBS', '(888) 999-1455', NULL, 'PA', 171);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Customer Experience Center', '(717) 783-3000', NULL, 'PA', 172);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Customer Experience Center Fax', '(717) 783-4294', 'Takes 24 hours', 'PA', 173);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Lien Payoff Email', 'ra-compenforfaxes@pa.gov', NULL, 'PA', 174);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Lien Payoff Fax', '(717) 772-5045', NULL, 'PA', 175);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'General', '(401) 222-1040', NULL, 'RI', 176);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Collections', '(401) 574-8941', NULL, 'RI', 177);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax', '(401) 574-8915', NULL, 'RI', 178);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'General', '(803) 898-5000', NULL, 'SC', 179);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Collections', '(803) 898-5611', NULL, 'SC', 180);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax', '(803) 737-5957', NULL, 'SC', 181);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'General', '(615) 253-0600', NULL, 'TN', 182);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Sales Tax General', '(800) 252-5555', NULL, 'TX', 183);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'General', '(801) 297-2200', NULL, 'UT', 184);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax', '(801) 297-6358', NULL, 'UT', 185);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax — POAs', '(801) 297-6202', 'Use this fax for POAs', 'UT', 186);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Collections', '(804) 367-8045', NULL, 'VA', 187);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Customer Service', '(804) 367-8031', NULL, 'VA', 188);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax', '(804) 254-6113', NULL, 'VA', 189);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Customer Service Center', '(202) 727-4829', NULL, 'DC', 190);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax', '(202) 442-6689', NULL, 'DC', 191);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Compliance', '(304) 558-8753', NULL, 'WV', 192);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Tax Practitioner', '(304) 558-0269', NULL, 'WV', 193);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Mail POA', 'West Virginia State Tax Dept., Legal Division District Officer, PO Box 1005, Charleston, WV 25328', NULL, 'WV', 194);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Central Compliance', '(608) 266-7879', NULL, 'WI', 195);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Fax', '(608) 267-0834', NULL, 'WI', 196);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Customer Service Center Main Line', '(307) 777-7311', NULL, 'WY', 197);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Sales Tax', '307-777-5544', NULL, 'WY', 198);
INSERT INTO irs_reference (category, title, content, notes, state, sort_order) VALUES ('State Info', 'Email', 'dor@wyo.org', NULL, 'WY', 199);
